apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotefrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotefrontend
  template:
    metadata:
      labels:
        app: coyotefrontend
    spec:
      containers:
        - name: frontend
          image: peterheywood708/coyotefrontend:main
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: config-js
              mountPath: /usr/share/nginx/html/config
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-js
          configMap:
            name: coyotefe-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotedb
  template:
    metadata:
      labels:
        app: coyotedb
    spec:
      containers:
        - name: db
          image: peterheywood708/coyotedb:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: coyotedb-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
