apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotefrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotefrontend
  template:
    metadata:
      labels:
        app: coyotefrontend
    spec:
      containers:
        - name: frontend
          image: peterheywood708/coyotefrontend:main
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: config-js
              mountPath: /usr/share/nginx/html/config
              readOnly: true
            - name: config-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-js
          configMap:
            name: coyotefe-config
        - name: config-nginx
          configMap:
            name: coyotefe-nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotedb
  template:
    metadata:
      labels:
        app: coyotedb
    spec:
      containers:
        - name: db
          image: peterheywood708/coyotedb:main
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: coyotedb-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotes3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotes3
  template:
    metadata:
      labels:
        app: coyotes3
    spec:
      containers:
        - name: db
          image: peterheywood708/coyotes3:main
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: coyotes3-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotesqs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotesqs
  template:
    metadata:
      labels:
        app: coyotesqs
    spec:
      containers:
        - name: db
          image: peterheywood708/coyotesqs:main
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: coyotesqs-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
