apiVersion: v1
kind: Service
metadata:
  name: coyotefrontend-service
spec:
  selector:
    app: coyotefrontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: coyotedb-service
spec:
  selector:
    app: coyotedb
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: coyotes3-service
spec:
  selector:
    app: coyotes3
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
